name: elearningapp_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.9.2
  video_player_web: ^2.1.3
  chewie: ^1.7.5
  dotted_border: ^2.0.0+2
  flame: ^1.14.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.8
  flame_forge2d: ^0.19.0+4
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/owl.png
    - lib/assets/play.png
    - lib/assets/video.png
    - lib/assets/popularRead.png
    - lib/assets/popularPlay.png
    - lib/assets/puzzle.jpg
    - lib/assets/trivia.jpg
    - lib/assets/quiz.jpg
    - lib/assets/spaceExplorer.jpg
    - lib/assets/solarSystem.jpg
    - lib/assets/animal.jpg
    - lib/assets/spaceBook.jpg
    - lib/assets/periodicTable.jpg
    - lib/assets/humanBodySystems.jpg
    - lib/assets/lifeBook.jpg
    - lib/assets/earthAndSpace.jpg
    - lib/assets/chemistry.jpg
    - lib/assets/BeautifulSpace.jpg
